version: "2"
run:
  timeout: 5m
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - thelper
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
