name: integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - tools/**
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - tools/**
      - README.md

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.23"
      - name: Build
        if: matrix.os == 'ubuntu-22.04'
        run: make build
      - name: build-windows
        if: matrix.os == 'windows-latest'
        run: make build-exe
      - name: Run Integration Tests
        run: make integration